#!/bin/ash

# Beep
echo -e "\007" 

# Hello
echo "" 
echo " Mini ARCOM Linux" 
echo ""
echo " ISEP, 2006-2013"
echo ""

PATH=/bin
export PATH

mount -t proc none /proc
mount -t devpts /dev/pts /dev/pts

# Insert Modules
insmod /modules/usbcore.o
insmod /modules/usb-storage.o
#insmod /modules/usb-ohci.o

sleep 3

mount -t vfat /dev/hda1 /pendrive

# Shell
/bin/ash

